config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :movements

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movements

  INCOME = 'ingreso'
  EXPENSE = 'gasto'

  def self.types
    [INCOME, EXPENSE]
  end
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
    @types = Category.types
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def new
    @category = Category.new
    @types = Category.types
  end

  def create
    @category = Category.new(category_params)
    @category.save

    redirect_to @category
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :category_type)
  end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  def index
    @movements = Movement.all
  end

  def new
    @movement = Movement.new
  end

  def create
    @movement = Movement.new(movement_params)
    @movement.save!
    redirect_to movement_path(@movement)
  end

  def edit
    @movement = movement
  end

  def update
    movement.update(movement_params)
    redirect_to movement_path(@movement)
  end

  def destroy
    movement.destroy
    redirect_to movements_path
  end

  def show
    movement
  end

  private
  def movement_params
    params.require(:movement).permit(:category_id, :value, :description)
  end

  def movement
    @movement ||= Movement.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<%= form_with(model: @category, local: true) do |form| %>
  <p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  </p>

  <p>
  <%= form.label :category_type %><br>
  <%= form.select :category_type, @types %>
  </p>

  <p>
  <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1> Categories </h1>

<table>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.category_type %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "New Category", new_category_path %>

app/views/categories/new.html.erb
<%= form_for @category, url: {action: "create"} do |form| %>
  <p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  </p>

  <p>
  <%= form.label :category_type %><br>
  <%= form.select :category_type, @types %>
  </p>

  <p>
  <%= form.submit %>
  </p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p><%= @category.category_type %></p>

<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movements/_form.html.erb
  <p>
<%=form_for @movement do |form|%>
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name, @movement.category_id), include_blank: true%>
  </p>
  <p>
    <%= form.label :description %>
    <%= form.text_field :description%>
  </p>
  <p>
    <%= form.label :value %>
    <%= form.number_field :value%>
  </p>

  <p><%=form.submit%></p>

<%end%>

app/views/movements/edit.html.erb
<%= render 'form'%>

app/views/movements/index.html.erb
<h1> Movements </h1>

<ol>
  <% @movements.each do |movement| %>
    <li>
      <ul>
        <li><label>Category:</label><%= movement.category.name.capitalize%></li>
        <li><label>Value:</label><%= movement.value%></li>
        <li><label>Description:</label><%= movement.description%></li>
        <li><%=link_to 'Edit', edit_movement_path(movement)%></li>
        <li><%=link_to 'Delete', movement_path(movement), method: :delete%></li>
      </ul>
    </li>
  <%end%>
</ol>

app/views/movements/new.html.erb
<%= render 'form'%>

app/views/movements/show.html.erb
<label> Category: </label>
<p><%= @movement.category.name %></p>

<label> Value: </label>
<p><%= @movement.value %></p>

<label> Description: </label>
<p><%= @movement.description %></p>